FROM ubuntu:20.04 AS builder

COPY --from=shuehchoulu/php-extensions:8.2-ubuntu-20.04-grpc-1.60.0 /grpc.so /grpc.so

RUN apt update; \
    apt install -y software-properties-common; \
    add-apt-repository -y ppa:ondrej/php; \
    apt-get install -y --no-install-recommends php8.2 libstdc++6; \
    mv /grpc.so /usr/local/lib/php/extensions/no-debug-non-zts-20220819/grpc.so
