FROM php:8.2-cli-alpine3.18

COPY --from=shuehchoulu/php-extensions:8.2-alpine-3.18-grpc-1.60.0 /grpc.so /grpc.so

RUN apk add --no-cache libstdc++; \
    mv /grpc.so $(php-config --extension-dir)/grpc.so; \
    docker-php-ext-enable grpc.so

RUN php -r 'use Grpc\Timeval; var_dump(Timeval::now());'
